In [1]:
import numpy as np    
import time

In [2]:
# Creating a matrix
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print("Matrix A:\n", A)

# Printing the order (dimensions) of the matrix
print("Order (dimensions) of A: ",A.shape)
print("Number of rows in A: ",A.shape[0])
print("Number of columns in A: ",A.shape[1])


Matrix A:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Order (dimensions) of A:  (4, 3)
Number of rows in A:  4
Number of columns in A:  3


In [3]:
# Scalar operations on a numpy array

print("A + 2 =\n", A + 2)
print("A - 2 =\n", A - 2)
print("A * 2 =\n", A * 2)   
print("A / 2 =\n", A / 2)

A + 2 =
 [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
A - 2 =
 [[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
A * 2 =
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]
A / 2 =
 [[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]
 [5.  5.5 6. ]]


In [4]:
def dot_fn(a, b): # Computing the dot product of two vectors using a for loop
    if a.shape[0] != b.shape[0]:
        print("Enter vectors of the same size")
        return
    sum = 0
    for i in range(a.shape[0]):
        sum = sum + a[i] * b[i]
    return sum

In [5]:
# Dot product of two vectors using dot_fn
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
c = dot_fn(a, b)
print("dot_fn(a, b) = ",c)

dot_fn(a, b) =  24


In [6]:
# Dot product of two vectors using numpy dot function
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
d1 = np.dot(a, b)
print("np.dot(a, b) = ",d1) 
d2 = np.dot(b, a)
print("np.dot(b, a) = ",d2) 

np.dot(a, b) =  24
np.dot(b, a) =  24


In [7]:
size = 10**7 # Length of the vectors

# Set random seed for reproducibility
np.random.seed(1)

a = np.random.randint(-10, 11, size)  # very large arrays
b = np.random.randint(-10, 11, size)
#print(a)
#print(b)


print("Shape of a: ",a.shape)
print("Shape of b: ",b.shape)

start_time = time.time()  # capture start time
c = np.dot(a, b)
end_time = time.time()  # capture end time
dot_time = end_time - start_time

print("np.dot(a, b) = ",c)
print("Vectorized version duration: ", dot_time,"sec")

start_time = time.time()  # capture start time
c = dot_fn(a,b)
end_time = time.time()  # capture end time
loop_time = end_time - start_time

print("dot_fn(a, b) = ",c)
print("Loop version duration: ", loop_time,"sec")


speedup = loop_time / dot_time
print(f"\nVectorized code is {speedup:.2f} times faster than the for loop code.")

Shape of a:  (10000000,)
Shape of b:  (10000000,)
np.dot(a, b) =  -39561
Vectorized version duration:  0.01549839973449707 sec
dot_fn(a, b) =  -39561
Loop version duration:  2.752110481262207 sec

Vectorized code is 177.57 times faster than the for loop code.


In [8]:
# Matrix multiplication: np.dot(), np.matmul() / @, and * (element-wise)

B = np.array([[1, 2], [3, 1]])
C = np.array([[4, 1], [2, 2]])

# np.dot() works for matrix multiplication...
ProdBC_dot = np.dot(B, C)

# ...but @ (same as np.matmul()) is the standard, more readable way to write it
ProdBC_at = B @ C
ProdBC_matmul = np.matmul(B, C)

# * is NOT matrix multiplication -- it multiplies element-by-element
ProdBC_elementwise = B * C

print("B @ C (matrix mult.) =\n", ProdBC_at)
print("np.dot(B, C) (same result) =\n", ProdBC_dot)
print("np.matmul(B, C) (same result) =\n", ProdBC_matmul)
print("B * C (element-wise, different!) =\n", ProdBC_elementwise)

B @ C (matrix mult.) =
 [[ 8  5]
 [14  5]]
np.dot(B, C) (same result) =
 [[ 8  5]
 [14  5]]
np.matmul(B, C) (same result) =
 [[ 8  5]
 [14  5]]
B * C (element-wise, different!) =
 [[4 2]
 [6 2]]


In [9]:
i = np.array([[0, -1], [1, 0]])    # Matrix corresponding to complex number i
print(i @ i)

[[-1  0]
 [ 0 -1]]


In [10]:
i = np.array([[0, -1], [1, 0]]) 
v = np.array([-1, 0])
print(i @ v)

[ 0 -1]


# Exercise

Write a code to rotate the vector (0, -1) by 90 degrees. Write your interpretation.


In [11]:
v = np.array([0, -1])

# 90-degree counterclockwise rotation matrix
theta = np.pi / 2
R = np.array([
    [np.cos(theta), -np.sin(theta)],
    [np.sin(theta),  np.cos(theta)]
])

rotated_v = R @ v

print(rotated_v)

[ 1.000000e+00 -6.123234e-17]
