In [1]:
import numpy as np

In [2]:
def elementary_decomposition(A):
    A = np.array(A, dtype=float)
    n = A.shape[0]
    
    # Store inverses of elementary matrices
    elementary_matrices = []
    
    # Step 1: Scale first row
    if A[0,0] != 1:
        E1_inv = np.eye(n)
        E1_inv[0,0] = A[0,0]
        elementary_matrices.append(E1_inv)
        A[0] = A[0] / A[0,0]
    
    # Step 2: Eliminate below pivot
    if A[1,0] != 0:
        factor = A[1,0]
        E2_inv = np.eye(n)
        E2_inv[1,0] = factor
        elementary_matrices.append(E2_inv)
        A[1] = A[1] - factor * A[0]
    
    # Step 3: Scale second row
    if A[1,1] != 1:
        E3_inv = np.eye(n)
        E3_inv[1,1] = A[1,1]
        elementary_matrices.append(E3_inv)
        A[1] = A[1] / A[1,1]
    
    # Step 4: Eliminate above pivot
    if A[0,1] != 0:
        factor = A[0,1]
        E4_inv = np.eye(n)
        E4_inv[0,1] = factor
        elementary_matrices.append(E4_inv)
        A[0] = A[0] - factor * A[1]
    
    return elementary_matrices

In [3]:
# Example matrix
A = [[4, 3],[2, 1]]
matrices = elementary_decomposition(A)

In [4]:
# Verify the product
product = np.eye(2)
for M in matrices:
    product = product @ M

In [5]:
print("Elementary matrices (in order):")
for i, M in enumerate(matrices, start=1):
    print(f"E{i}^-1:\n{M}\n")

print("Product of elementary matrices:")
print(product)

Elementary matrices (in order):
E1^-1:
[[4. 0.]
 [0. 1.]]

E2^-1:
[[1. 0.]
 [2. 1.]]

E3^-1:
[[ 1.   0. ]
 [ 0.  -0.5]]

E4^-1:
[[1.   0.75]
 [0.   1.  ]]

Product of elementary matrices:
[[4. 3.]
 [2. 1.]]


# EXERCISE

The digit root of a number is a single-digit number obtained by repeatedly summing the digits of a number until a single-digit result is achieved. Form an elementary decomposition of the matrix $$A =
\begin{pmatrix}
5 & K \\
2 & K
\end{pmatrix}
$$

where K is the digit root of your roll number. Illustrate the effect of multiplying the vector $(1,0)$ by $A$ geometrically using the elementary transformations. Verify your answer algebraically.

In [6]:
roll_number = 59

def digit_root(n):
    n = abs(n)
    while n >= 10:
        n = sum(int(d) for d in str(n))
    return n

K = digit_root(roll_number)
print("K (digit root of roll number) =", K)


A_ex = [[5, K], [2, K]]
print("A =")
print(np.array(A_ex))

matrices_ex = elementary_decomposition(A_ex)

print("Elementary matrices (in order):")
for i, M in enumerate(matrices_ex, start=1):
    print(f"E{i}^-1:\n{M}\n")


product_ex = np.eye(2)
for M in matrices_ex:
    product_ex = product_ex @ M

print("Product of elementary matrices:")
print(product_ex)


v = np.array([1.0, 0.0])
print("v0 =", v)

for i, M in enumerate(reversed(matrices_ex), start=1):
    label = len(matrices_ex) - i + 1
    v = M @ v
    print(f"after applying E{label}^-1: v = {v}")

print("\nFinal transformed vector A @ (1,0):", v)


direct = np.array(A_ex, dtype=float) @ np.array([1.0, 0.0])
print("Direct A @ (1,0) =", direct)
print("Matches step-by-step result:", np.allclose(direct, v))

K (digit root of roll number) = 5
A =
[[5 5]
 [2 5]]
Elementary matrices (in order):
E1^-1:
[[5. 0.]
 [0. 1.]]

E2^-1:
[[1. 0.]
 [2. 1.]]

E3^-1:
[[1. 0.]
 [0. 3.]]

E4^-1:
[[1. 1.]
 [0. 1.]]

Product of elementary matrices:
[[5. 5.]
 [2. 5.]]
v0 = [1. 0.]
after applying E4^-1: v = [1. 0.]
after applying E3^-1: v = [1. 0.]
after applying E2^-1: v = [1. 2.]
after applying E1^-1: v = [5. 2.]

Final transformed vector A @ (1,0): [5. 2.]
Direct A @ (1,0) = [5. 2.]
Matches step-by-step result: True
