In [1]:
import numpy as np

In [2]:
# ----------------------------------------
# Define linear transformations as functions
# ----------------------------------------

def T1(v):
    """
    Linear transformation T1: Scaling
    Doubles the x-coordinate, keeps y the same
    """
    x, y = v
    return np.array([2*x, y])

def T2(v):
    """
    Linear transformation T2: Rotation by 90 degrees counterclockwise
    (x, y) -> (-y, x)
    """
    x, y = v
    return np.array([-y, x])

In [3]:
# Composition of functions
def composition(v):
    return T2(T1(v))

In [4]:
# ----------------------------------------
# Derive the matrices for T1 and T2
# (using the images of the basis vectors e1=(1,0), e2=(0,1))
# ----------------------------------------

e1 = np.array([1, 0])
e2 = np.array([0, 1])

# Build matrices column by column
M1 = np.column_stack((T1(e1), T1(e2)))
M2 = np.column_stack((T2(e1), T2(e2)))

M_combined = M2 @ M1

print("Matrix for T1:\n", M1)
print("Matrix for T2:\n", M2)
print("Matrix product M2*M1:\n", M_combined)

Matrix for T1:
 [[2 0]
 [0 1]]
Matrix for T2:
 [[ 0 -1]
 [ 1  0]]
Matrix product M2*M1:
 [[ 0 -1]
 [ 2  0]]


In [5]:
# Function to apply the matrix product on a vector
def matrix_function(v):
    return M_combined @ v

In [6]:
# ----------------------------------------
# Test on several inputs
# ----------------------------------------
vectors = [np.array([1,0]), np.array([0,1]), np.array([1,2]), np.array([-1,3])]

print("Comparing (T2 ∘ T1)(v) with (M2 M1)(v):\n")
for v in vectors:
    f1 = composition(v)
    f2 = matrix_function(v)
    print(f"Input: {v}")
    print(f"  Composition result = {f1}")
    print(f"  Matrix product result = {f2}")
    print(f"  Same? {np.array_equal(f1, f2)}\n")

Comparing (T2 ∘ T1)(v) with (M2 M1)(v):

Input: [1 0]
  Composition result = [0 2]
  Matrix product result = [0 2]
  Same? True

Input: [0 1]
  Composition result = [-1  0]
  Matrix product result = [-1  0]
  Same? True

Input: [1 2]
  Composition result = [-2  2]
  Matrix product result = [-2  2]
  Same? True

Input: [-1  3]
  Composition result = [-3 -2]
  Matrix product result = [-3 -2]
  Same? True

